version: '3.2'

services:
  mongo_db: 
    image: mongo        
    ports:
      - "27018:27017"
#----------------------------------------
  mongoapi:
    image: iotdatabase:latest
    deploy:
        replicas: 3
        restart_policy:
            condition: on-failure
    ports:
      - "8000:80"
#----------------------------------------
  iotregister:
    image: iotregister:latest
    build: .
    deploy:
      replicas: 3
    ports:
      - "8001:80"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

#----------------------------------------
  iotweb:
    image: iotweb:latest
    deploy:
      replicas: 3
      restart_policy:
          condition: on-failure
    ports:
      - "8002:80"

#--------------KAFKA-ZOOKEEPER-----------
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
# KAFKA_AUTO_CREATE_TOPICS_ENABLE is true by default
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "FailureTopic:1:3, RegisterTopic:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
